/**
 * The measurement: eight wirings, two conditions, twelve probes.
 *
 * ---------------------------------------------------------------------------
 * What the table is, and what it is not
 * ---------------------------------------------------------------------------
 * Every cell below is a *claim about Chromium*, and `fidelity.spec.ts` checks
 * all 192 of them against a real browser on every run. Nothing here is derived
 * from a changelog, from Playwright's documentation, or from what the author
 * expected — several cells are the opposite of the first draft, and the
 * findings at the bottom of this file are the reason the draft was wrong.
 *
 * Writing the table down rather than generating it from the run is deliberate,
 * and it is the same choice `ct/README.md` makes about jsdom: a matrix
 * generated by the measurement agrees with the measurement by construction and
 * can never fail. This one can, and when it does, one of two things is true —
 * Playwright changed, or somebody changed a wiring without noticing what it
 * cost. Both are worth a red build.
 *
 * ---------------------------------------------------------------------------
 * The findings are derived, not declared
 * ---------------------------------------------------------------------------
 * {@link FINDINGS} holds the claims this directory's README makes in prose.
 * Each one is a function over the table rather than a sentence, so the README
 * cannot drift from the measurement: change a cell and the finding that
 * depended on it fails in `matrix.test.ts`, before anybody reads the paragraph
 * it contradicts.
 */

import { PROBE_NAMES, probeByName, type ProbeName } from './probes.ts'
import { CONDITIONS, WIRING_NAMES, type Condition, type WiringName } from './wirings.ts'

/** One wiring's answers under one condition. */
export type Row = Readonly<Record<ProbeName, string>>

/** The whole table, keyed by wiring and then by condition. */
export type Matrix = Readonly<Record<WiringName, Readonly<Record<Condition, Row>>>>

export const MATRIX: Matrix = {
  live: {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'reached',
      'drifted-get': 'origin',
      'unrecorded-get': 'origin',
      'query-variance': 'origin',
      'post-echo': 'echoes-sent',
      'retry-recovers': 'recovered',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'failed',
      'reaches-origin': 'not-reached',
      'drifted-get': 'failed',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
  },
  'stub-fulfill': {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'stub',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stub',
      'unrecorded-get': 'origin',
      'query-variance': 'stub',
      'post-echo': 'stub',
      'retry-recovers': 'first-try',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'stub',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stub',
      'unrecorded-get': 'failed',
      'query-variance': 'stub',
      'post-echo': 'stub',
      'retry-recovers': 'first-try',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
  },
  'har-abort': {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
  },
  'har-fallback': {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'origin',
      'query-variance': 'origin',
      'post-echo': 'echoes-sent',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
  },
  'har-whole-page': {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
  },
  'abort-api': {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'failed',
      'reaches-origin': 'not-reached',
      'drifted-get': 'failed',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'failed',
      'reaches-origin': 'not-reached',
      'drifted-get': 'failed',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'online',
      'offline-event': 'silent',
      'observed-by-test': 'observed',
    },
  },
  offline: {
    connected: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'failed',
      'reaches-origin': 'not-reached',
      'drifted-get': 'failed',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'offline',
      'offline-event': 'fired',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'failed',
      'static-asset': 'failed',
      'known-get': 'failed',
      'reaches-origin': 'not-reached',
      'drifted-get': 'failed',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'offline',
      'offline-event': 'fired',
      'observed-by-test': 'observed',
    },
  },
  'offline-har': {
    connected: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'offline',
      'offline-event': 'fired',
      'observed-by-test': 'observed',
    },
    severed: {
      document: 'origin',
      'static-asset': 'origin',
      'known-get': 'origin',
      'reaches-origin': 'not-reached',
      'drifted-get': 'stale',
      'unrecorded-get': 'failed',
      'query-variance': 'failed',
      'post-echo': 'failed',
      'retry-recovers': 'failed',
      'online-flag': 'offline',
      'offline-event': 'fired',
      'observed-by-test': 'observed',
    },
  },
}

/** One cell, by the three coordinates that name it. */
export const cell = (wiring: WiringName, condition: Condition, probe: ProbeName): string =>
  MATRIX[wiring][condition][probe]

/** The probes on which two wirings disagree, under one condition. */
export function differences(
  left: WiringName,
  right: WiringName,
  condition: Condition,
): readonly ProbeName[] {
  return PROBE_NAMES.filter((probe) => cell(left, condition, probe) !== cell(right, condition, probe))
}

/** The wirings whose answer to a probe is one of the given words. */
export function wiringsAnswering(
  condition: Condition,
  probe: ProbeName,
  ...outcomes: readonly string[]
): readonly WiringName[] {
  return WIRING_NAMES.filter((wiring) => outcomes.includes(cell(wiring, condition, probe)))
}

/**
 * Cells the probe's own vocabulary does not allow.
 *
 * The table is a nested record of strings, and TypeScript is content with any
 * string in any cell. This is the check that is not — a cell holding
 * `'stalee'` is a typo the compiler cannot see and this function can.
 */
export function invalidCells(): readonly string[] {
  const problems: string[] = []

  for (const wiring of WIRING_NAMES) {
    for (const condition of CONDITIONS) {
      for (const probe of PROBE_NAMES) {
        const outcomes = probeByName(probe)?.outcomes ?? []
        const value = cell(wiring, condition, probe)

        if (!outcomes.includes(value)) {
          problems.push(
            `${wiring}/${condition}/${probe} is ${JSON.stringify(value)}, which is not one of ` +
              outcomes.map((outcome) => JSON.stringify(outcome)).join(', '),
          )
        }
      }
    }
  }

  return problems
}

/**
 * Render one condition's half of the table as Markdown.
 *
 * `README.md` holds the output of this function verbatim, and `readme.test.ts`
 * re-renders it and asserts the file still contains it. That is a stronger
 * guarantee than the usual "the README mentions the number": the published
 * table cannot disagree with the data in any cell, in any row order, or by a
 * column somebody added and forgot to document — the two are the same string
 * or the build is red.
 *
 * Probes are rows and wirings are columns, which is the transpose of how the
 * data is stored. Eight columns fit a page and twelve do not, and the reading
 * people do here is down a column: "what does this wiring cost me".
 */
export function renderTable(condition: Condition): string {
  const header = `| probe | ${WIRING_NAMES.join(' | ')} |`
  const rule = `| --- | ${WIRING_NAMES.map(() => '---').join(' | ')} |`
  const rows = PROBE_NAMES.map(
    (probe) => `| \`${probe}\` | ${WIRING_NAMES.map((wiring) => cell(wiring, condition, probe)).join(' | ')} |`,
  )

  return [header, rule, ...rows].join('\n')
}

/**
 * A claim the README makes, stated as a question to the table.
 *
 * `holds` returns the empty string when the claim is true and an explanation
 * when it is not, so a failing finding says what the table actually contains
 * rather than `expected true to be false`.
 */
export interface Finding {
  readonly id: string
  /** The claim, in the words the README uses. */
  readonly claim: string
  readonly holds: () => string
}

const listEquals = (actual: readonly string[], expected: readonly string[]): string => {
  const left = [...actual].sort().join(', ')
  const right = [...expected].sort().join(', ')

  return left === right ? '' : `got [${left}], expected [${right}]`
}

/** The four wirings that replay the committed recording.
 *
 * Written down rather than derived, because three of the findings below are
 * *about* what the replaying wirings have in common, and deriving the list
 * from one of those properties would make those findings say "the wirings with
 * this property have this property".
 */
export const REPLAY_WIRINGS: readonly WiringName[] = [
  'har-abort',
  'har-fallback',
  'har-whole-page',
  'offline-har',
]

export const FINDINGS = [
  {
    id: 'belief-is-the-only-difference',
    claim:
      'With no network behind either of them, aborting every API request and ' +
      'emulating a disconnection differ on nothing except what the page believes.',
    holds: () =>
      listEquals(differences('abort-api', 'offline', 'severed'), ['online-flag', 'offline-event']),
  },
  {
    id: 'fallback-leaks-and-severing-shows-it',
    claim:
      "`notFound: 'fallback'` and `notFound: 'abort'` are the same wiring with " +
      'no network behind them, and differ on exactly the three probes the ' +
      'fallback answered over a socket.',
    holds: () => {
      const severed = differences('har-abort', 'har-fallback', 'severed')

      if (severed.length !== 0) {
        return `the two rows differ under severed on [${severed.join(', ')}], expected none`
      }

      return listEquals(differences('har-abort', 'har-fallback', 'connected'), [
        'unrecorded-get',
        'query-variance',
        'post-echo',
      ])
    },
  },
  {
    id: 'every-replay-is-stale',
    claim:
      'Every wiring that replays the recording answers the drifted endpoint with the old shape.',
    holds: () => listEquals(wiringsAnswering('connected', 'drifted-get', 'stale'), REPLAY_WIRINGS),
  },
  {
    id: 'a-replay-is-indistinguishable-from-the-origin',
    claim:
      'On the unchanged endpoint, a replayed response and a live one are the ' +
      'same answer; only the origin can say which happened.',
    holds: () => {
      const answeredByOrigin = wiringsAnswering('connected', 'known-get', 'origin')
      const reached = wiringsAnswering('connected', 'reaches-origin', 'reached')

      return answeredByOrigin.length > reached.length
        ? ''
        : `${answeredByOrigin.length} wirings answer with an origin body and ${reached.length} ` +
            'of them reached the origin — the probe has stopped separating them'
    },
  },
  {
    id: 'a-stub-deletes-the-retry',
    claim: "A hand-written stub answers on the first attempt, so the client's retry never runs.",
    holds: () =>
      cell('stub-fulfill', 'connected', 'retry-recovers') === 'first-try' &&
      cell('live', 'connected', 'retry-recovers') === 'recovered'
        ? ''
        : 'the stub and the origin no longer disagree about how many attempts it took',
  },
  {
    id: 'the-recorded-failure-is-the-one-that-replays',
    claim:
      'The recording holds both answers the flaky endpoint gave — a 503 and ' +
      'then a 200 — and every replaying wiring serves the 503 to both attempts, ' +
      'so the retry that recovered against the origin never recovers against the recording.',
    holds: () => {
      const recovering = REPLAY_WIRINGS.filter((wiring) =>
        CONDITIONS.some((condition) => cell(wiring, condition, 'retry-recovers') !== 'failed'),
      )

      return recovering.length === 0
        ? ''
        : `${recovering.join(', ')} no longer fail the retry probe against the recording`
    },
  },
  {
    id: 'a-recording-is-keyed-on-the-whole-request',
    claim:
      'A cache-busting query and a POST body the recording has not seen are ' +
      'both misses: the match is on the whole request, not on the endpoint.',
    holds: () => {
      const matched = REPLAY_WIRINGS.filter(
        (wiring) =>
          cell(wiring, 'severed', 'query-variance') !== 'failed' ||
          cell(wiring, 'severed', 'post-echo') !== 'failed',
      )

      return matched.length === 0
        ? ''
        : `${matched.join(', ')} answered a request the recording does not hold`
    },
  },
  {
    id: 'the-feared-answer-does-not-happen',
    claim:
      "No cell reads `echoes-recorded`: Playwright's matcher compares the " +
      'request body, so a POST whose body has changed misses loudly rather ' +
      'than being answered with somebody else\'s recording.',
    holds: () => {
      const cells = WIRING_NAMES.flatMap((wiring) =>
        CONDITIONS.filter((condition) => cell(wiring, condition, 'post-echo') === 'echoes-recorded').map(
          (condition) => `${wiring}/${condition}`,
        ),
      )

      return cells.length === 0 ? '' : `${cells.join(', ')} answered with the recorded word`
    },
  },
  {
    id: 'only-a-whole-page-replay-survives',
    claim:
      'With no network, only the two wirings that replay the document keep the ' +
      'application loading at all.',
    holds: () =>
      listEquals(wiringsAnswering('severed', 'document', 'origin'), [
        'har-whole-page',
        'offline-har',
      ]),
  },
  {
    id: 'counting-requests-proves-nothing',
    claim:
      "`page.on('request')` fires in every cell of the table, including the " +
      'ones where nothing left the browser.',
    holds: () => {
      const missing = WIRING_NAMES.flatMap((wiring) =>
        CONDITIONS.filter(
          (condition) => cell(wiring, condition, 'observed-by-test') !== 'observed',
        ).map((condition) => `${wiring}/${condition}`),
      )

      return missing.length === 0 ? '' : `not observed in ${missing.join(', ')}`
    },
  },
  {
    id: 'offline-does-not-mean-empty',
    claim:
      'Emulated offline stops the connection, not the routing: a fulfilled ' +
      'request still answers, so an offline-capable application can be driven ' +
      'while the page believes it is disconnected.',
    holds: () =>
      cell('offline-har', 'severed', 'online-flag') === 'offline' &&
      cell('offline-har', 'severed', 'known-get') === 'origin' &&
      cell('offline', 'severed', 'known-get') === 'failed'
        ? ''
        : 'the two offline rows no longer disagree about whether a fulfilled request answers',
  },
] as const satisfies readonly Finding[]

export type FindingId = (typeof FINDINGS)[number]['id']
