import { test as base, expect } from '@playwright/test'
import type { Browser, BrowserContext, Page } from '@playwright/test'
import { existsSync } from 'node:fs'
import path from 'node:path'

export type UserRole = 'admin' | 'user'

export interface AuthUser {
  id: string
  email: string
  name: string
  role: UserRole
}

interface LoginResponse {
  user: AuthUser
  accessToken: string
  refreshToken: string
}

export const AUTH_DIR = path.join(process.cwd(), '.auth')

export const AUTH_STORAGE_PATHS = {
  admin: path.join(AUTH_DIR, 'admin.json'),
  user: path.join(AUTH_DIR, 'user.json'),
} as const satisfies Record<UserRole, string>

export const AUTH_CREDENTIALS = {
  admin: { email: 'admin@example.com', password: 'password' },
  user: { email: 'alice@example.com', password: 'password' },
} as const satisfies Record<UserRole, { email: string; password: string }>

/**
 * Navigate to the app origin so localStorage is writable, then inject tokens.
 * The page is closed immediately after — callers create their own page via context.
 */
async function injectAuthTokens(
  context: BrowserContext,
  data: LoginResponse,
  origin: string,
): Promise<void> {
  const page = await context.newPage()
  await page.goto(origin, { waitUntil: 'commit' })
  await page.evaluate((auth: LoginResponse) => {
    localStorage.setItem('auth.accessToken', auth.accessToken)
    localStorage.setItem('auth.refreshToken', auth.refreshToken)
    localStorage.setItem('auth.user', JSON.stringify(auth.user))
  }, data)
  await page.close()
}

/**
 * Build a browser context pre-loaded with auth tokens for the given role.
 *
 * Resolution order:
 * 1. Load storageState from `.auth/{role}.json` if present (generated by setup project).
 * 2. Fall back to a live POST /api/auth/login + localStorage injection.
 */
async function buildAuthContext(
  browser: Browser,
  role: UserRole,
  origin: string,
): Promise<BrowserContext> {
  const storagePath = AUTH_STORAGE_PATHS[role]

  if (existsSync(storagePath)) {
    return browser.newContext({ storageState: storagePath })
  }

  const context = await browser.newContext()
  const res = await context.request.post(`${origin}/api/auth/login`, {
    data: AUTH_CREDENTIALS[role],
  })

  if (!res.ok()) {
    await context.close()
    throw new Error(
      `Auth setup failed for role "${role}": HTTP ${res.status()} — ${await res.text()}`,
    )
  }

  const data = (await res.json()) as LoginResponse
  await injectAuthTokens(context, data, origin)
  return context
}

export interface AuthFixtures {
  /**
   * Overridable role option. Override per-describe or per-test:
   * @example test.use({ role: 'admin' })
   */
  role: UserRole
  /** Page pre-authenticated as the current `role`. */
  authenticatedPage: Page
  /** Convenience fixture: page always authenticated as admin. */
  adminPage: Page
  /** Convenience fixture: page always authenticated as user. */
  userPage: Page
}

export const test = base.extend<AuthFixtures>({
  // Declare as an option so callers can override with test.use({ role: 'admin' })
  role: ['user', { option: true }],

  authenticatedPage: async ({ browser, role, baseURL }, use) => {
    const origin = baseURL ?? 'http://localhost:5173'
    const context = await buildAuthContext(browser, role, origin)
    const page = await context.newPage()
    await use(page)
    await context.close()
  },

  adminPage: async ({ browser, baseURL }, use) => {
    const origin = baseURL ?? 'http://localhost:5173'
    const context = await buildAuthContext(browser, 'admin', origin)
    const page = await context.newPage()
    await use(page)
    await context.close()
  },

  userPage: async ({ browser, baseURL }, use) => {
    const origin = baseURL ?? 'http://localhost:5173'
    const context = await buildAuthContext(browser, 'user', origin)
    const page = await context.newPage()
    await use(page)
    await context.close()
  },
})

export { expect }
