/**
 * The recorded result of running every probe against every fault.
 *
 * GENERATED BY `pnpm fuzz:record` — edit `record.ts`, not this file.
 *
 * One row per (fault, probe) pair that found something, carrying the minimal
 * input that reproduces it. Two suites read this file and they read it for
 * opposite reasons:
 *
 *   - `corpus.test.ts` replays every witness against the fault it was found
 *     on. That is the regression gate, and it is milliseconds rather than the
 *     minutes a real campaign costs.
 *   - `detection.test.ts` re-runs the campaigns and fails if the live matrix
 *     disagrees with the rows below. That is what stops this file becoming a
 *     screenshot of a result that used to be true.
 *
 * `inputsTried` is how many inputs the campaign consumed before the probe
 * noticed anything; `foundLength` and `minimisedLength` are the witness
 * before and after `minimise.ts`, and `evaluations` is what that search cost
 * in predicate calls. The ratio between the first two is the number worth
 * looking at: it is why a fuzzer's raw output is unreadable and why nobody
 * should file one.
 */

import type { ProbeId } from './campaign.ts'
import { VARIANT_IDS, type VariantId } from './edits.ts'
import type { GeneratorId } from './generators.ts'

export /**
 * The four faults the generator comparison is run over.
 *
 * Four rather than sixteen because the point is qualitative and a campaign per
 * (fault, generator) pair is not free. Each one is here because it separates
 * the generators differently: a lexer fault only byte-level edits reach, a
 * structural fault only a schema-aware generator emits, a crash only deep
 * nesting provokes, and a validator fault two of the three reach. The oracle
 * is fixed per row so the row measures generators and nothing else.
 */
const CROSSOVER_CASES: readonly { variant: VariantId; probe: ProbeId }[] = [
  { variant: 'CONTROL_CHARACTER_ACCEPTED', probe: 'differential' },
  { variant: 'PROTOTYPE_POLLUTION', probe: 'differential' },
  { variant: 'NO_DEPTH_LIMIT', probe: 'crash' },
  { variant: 'UNKNOWN_KEY_IGNORED', probe: 'invariant' },
]

interface Crossover {
  variant: VariantId
  probe: ProbeId
  foundBy: GeneratorId[]
}

interface Detection {
  readonly variant: VariantId
  readonly probe: ProbeId
  /** Which check fired. `SUBJECT_THREW` means the subject never returned. */
  readonly reason: string
  readonly inputsTried: number
  /** The minimal input that reproduces it. Empty for `examples`, which generates none. */
  readonly witness: string
  readonly foundLength: number
  readonly minimisedLength: number
  readonly evaluations: number
}

export const DETECTIONS: readonly Detection[] = [
  {
    variant: "TRAILING_COMMA_IN_ARRAY_ACCEPTED",
    probe: "differential",
    reason: "ACCEPTED_WHAT_JSON_REJECTS",
    inputsTried: 1562,
    witness: "[3,]",
    foundLength: 6,
    minimisedLength: 4,
    evaluations: 35,
  },
  {
    variant: "TRAILING_COMMA_IN_ARRAY_ACCEPTED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "TRAILING_CONTENT_IGNORED",
    probe: "differential",
    reason: "ACCEPTED_WHAT_JSON_REJECTS",
    inputsTried: 62,
    witness: "00",
    foundLength: 5,
    minimisedLength: 2,
    evaluations: 7,
  },
  {
    variant: "TRAILING_CONTENT_IGNORED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "LEADING_ZERO_ACCEPTED",
    probe: "differential",
    reason: "ACCEPTED_WHAT_JSON_REJECTS",
    inputsTried: 410,
    witness: "00",
    foundLength: 7,
    minimisedLength: 2,
    evaluations: 11,
  },
  {
    variant: "LEADING_ZERO_ACCEPTED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "EXPONENT_PLUS_REJECTED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "CONTROL_CHARACTER_ACCEPTED",
    probe: "differential",
    reason: "ACCEPTED_WHAT_JSON_REJECTS",
    inputsTried: 578,
    witness: "{\"\":\"\",\"\t\":[\"\",\"\"],\"\":{\"\":true}}",
    foundLength: 131,
    minimisedLength: 32,
    evaluations: 2460,
  },
  {
    variant: "CONTROL_CHARACTER_ACCEPTED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "UNKNOWN_ESCAPE_PASSTHROUGH",
    probe: "differential",
    reason: "ACCEPTED_WHAT_JSON_REJECTS",
    inputsTried: 938,
    witness: "{\"\":\"\\s\",\"\":0,\"\":[\"\",\"\"],\"\":{\"\":true,\"\":1}}",
    foundLength: 120,
    minimisedLength: 43,
    evaluations: 1828,
  },
  {
    variant: "UNKNOWN_ESCAPE_PASSTHROUGH",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "SHORT_UNICODE_ESCAPE",
    probe: "roundtrip",
    reason: "REPARSE_DIFFERS",
    inputsTried: 38,
    witness: "{\"\":\"\",\"\":[\"\",\"\"],\"\ud800\":{\"\":1}}",
    foundLength: 119,
    minimisedLength: 29,
    evaluations: 1138,
  },
  {
    variant: "SHORT_UNICODE_ESCAPE",
    probe: "differential",
    reason: "VALUE_DIFFERS",
    inputsTried: 227,
    witness: "{\"\":\"\\u00e9\",\"s\":[\"\"],\"s\":{\"\":true,\"\":0.5}}",
    foundLength: 99,
    minimisedLength: 43,
    evaluations: 1356,
  },
  {
    variant: "SHORT_UNICODE_ESCAPE",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "DUPLICATE_KEY_FIRST_WINS",
    probe: "differential",
    reason: "VALUE_DIFFERS",
    inputsTried: 18,
    witness: "{\"\":7,\"\":0,\"\":0,\"\":{\"\":true,\"\":0}}",
    foundLength: 125,
    minimisedLength: 34,
    evaluations: 1777,
  },
  {
    variant: "DUPLICATE_KEY_FIRST_WINS",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "PROTOTYPE_POLLUTION",
    probe: "differential",
    reason: "VALUE_DIFFERS",
    inputsTried: 75,
    witness: "{\"\":\"\",\"\":{\"\":1},\"__proto__\":null}",
    foundLength: 187,
    minimisedLength: 34,
    evaluations: 782,
  },
  {
    variant: "PROTOTYPE_POLLUTION",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "NO_DEPTH_LIMIT",
    probe: "crash",
    reason: "THREW",
    inputsTried: 108,
    witness: "[".repeat(30000) + "]".repeat(30000),
    foundLength: 60000,
    minimisedLength: 60000,
    evaluations: 0,
  },
  {
    variant: "NO_DEPTH_LIMIT",
    probe: "roundtrip",
    reason: "SUBJECT_THREW",
    inputsTried: 108,
    witness: "[".repeat(30000) + "]".repeat(30000),
    foundLength: 60000,
    minimisedLength: 60000,
    evaluations: 0,
  },
  {
    variant: "NO_DEPTH_LIMIT",
    probe: "invariant",
    reason: "SUBJECT_THREW",
    inputsTried: 108,
    witness: "[".repeat(30000) + "]".repeat(30000),
    foundLength: 60000,
    minimisedLength: 60000,
    evaluations: 0,
  },
  {
    variant: "NO_DEPTH_LIMIT",
    probe: "examples",
    reason: "SUBJECT_THREW",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "NAME_PATTERN_UNANCHORED",
    probe: "invariant",
    reason: "ACCEPTED_INVALID",
    inputsTried: 480,
    witness: "{\"name\":\"cP\",\"retries\":1,\"timeoutMs\":1,\"tags\":[],\"limits\":{\"enabled\":false,\"ratio\":0.5}}",
    foundLength: 96,
    minimisedLength: 88,
    evaluations: 776,
  },
  {
    variant: "NAME_PATTERN_UNANCHORED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "INTEGER_CHECK_DROPPED",
    probe: "invariant",
    reason: "ACCEPTED_INVALID",
    inputsTried: 132,
    witness: "{\"name\":\"c\",\"retries\":1,\"timeoutMs\":1.5,\"tags\":[\"d\"],\"limits\":{\"enabled\":true,\"ratio\":0}}",
    foundLength: 102,
    minimisedLength: 89,
    evaluations: 1057,
  },
  {
    variant: "INTEGER_CHECK_DROPPED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "INTEGER_UPPER_BOUND_UNCHECKED",
    probe: "invariant",
    reason: "ACCEPTED_INVALID",
    inputsTried: 81,
    witness: "{\"name\":\"s\",\"retries\":100,\"timeoutMs\":1,\"tags\":[\"3\",\"4\",\"s\"],\"limits\":{\"enabled\":false,\"ratio\":0}}",
    foundLength: 125,
    minimisedLength: 98,
    evaluations: 1366,
  },
  {
    variant: "INTEGER_UPPER_BOUND_UNCHECKED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "RATIO_UPPER_BOUND_EXCLUSIVE",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "UNKNOWN_KEY_IGNORED",
    probe: "invariant",
    reason: "ACCEPTED_UNKNOWN_KEYS",
    inputsTried: 75,
    witness: "{\"name\":\"l\",\"retries\":0,\"timeoutMs\":3,\"tags\":[\"e\",\"2\"],\"limits\":{\"enabled\":false,\"ratio\":1},\"\":null}",
    foundLength: 187,
    minimisedLength: 100,
    evaluations: 2312,
  },
  {
    variant: "UNKNOWN_KEY_IGNORED",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
  {
    variant: "TAGS_SORTED_IN_PLACE",
    probe: "invariant",
    reason: "MUTATED_ITS_ARGUMENT",
    inputsTried: 9,
    witness: "{\"name\":\"c\",\"retries\":1,\"timeoutMs\":1,\"tags\":[\"4\",\"d\",\"1\"],\"limits\":{\"enabled\":true,\"ratio\":1}}",
    foundLength: 114,
    minimisedLength: 95,
    evaluations: 1905,
  },
  {
    variant: "TAGS_SORTED_IN_PLACE",
    probe: "examples",
    reason: "EXAMPLE_FAILED",
    inputsTried: 1,
    witness: "",
    foundLength: 0,
    minimisedLength: 0,
    evaluations: 0,
  },
]

/** Which probes noticed a given fault at all. */
export function probesThatFound(variant: VariantId): readonly ProbeId[] {
  return DETECTIONS.filter((detection) => detection.variant === variant).map(
    (detection) => detection.probe,
  )
}

/** The faults a given probe noticed. */
export function faultsFoundBy(probe: ProbeId): readonly VariantId[] {
  return DETECTIONS.filter((detection) => detection.probe === probe).map(
    (detection) => detection.variant,
  )
}

/** Every fault at least one probe noticed. */
export function faultsFound(): readonly VariantId[] {
  return VARIANT_IDS.filter((id) => DETECTIONS.some((detection) => detection.variant === id))
}

export const CROSSOVER: readonly Crossover[] = [
  {
    variant: "CONTROL_CHARACTER_ACCEPTED",
    probe: "differential",
    foundBy: ["mutate", "mixed"],
  },
  {
    variant: "PROTOTYPE_POLLUTION",
    probe: "differential",
    foundBy: ["grammar", "mixed"],
  },
  {
    variant: "NO_DEPTH_LIMIT",
    probe: "crash",
    foundBy: ["grammar", "mixed"],
  },
  {
    variant: "UNKNOWN_KEY_IGNORED",
    probe: "invariant",
    foundBy: ["mutate", "grammar", "mixed"],
  },
]
