/**
 * The measurement: what sharding a Playwright suite actually does.
 *
 * ---------------------------------------------------------------------------
 * The claim under test
 * ---------------------------------------------------------------------------
 * "`--shard=k/n` splits your tests across n machines, so n machines finish in
 * 1/n of the time." The first clause is true of the *test count* and false of
 * the *tests*; the second is false often enough to be worth measuring, and it
 * fails for a reason nobody looks for — a setting three lines up in the same
 * config file that has nothing to do with sharding in its name.
 *
 * Three tables below, each hand-written and each checked:
 *
 *   - {@link GROUP_SHAPES} — what the indivisible unit is, per file shape.
 *   - {@link SHARD_BALANCE} — what the resulting shards weigh, per shard count.
 *   - {@link SETUP_RUNS} — how often a `dependencies` project runs.
 *
 * `grouping.test.ts` checks all three against `shard.ts`, the model.
 * `partition.test.ts` checks the model against `playwright test --list
 * --shard`, the real thing. Writing the numbers out rather than printing them
 * from the model is the same choice `intercept/matrix.ts` makes and for the
 * same reason: a table generated by the measurement agrees with it by
 * construction and can never go red.
 */

import { FIXTURE_FILES } from './fixture.ts'

/** The file shapes the fixture covers, named after the spec file that is one. */
export type Shape = 'plain' | 'hooked' | 'serial' | 'parallel-block'

/** What Playwright refuses to split, for a file of this shape. */
export type Unit =
  /** The whole file: one group, one worker, one shard. */
  | 'file'
  /** One group per test; the file is free to straddle a shard boundary. */
  | 'test'
  /** The `describe.serial` block, whatever else is configured. */
  | 'block'
  /** `ceil(tests / shardTotal)` tests — a unit that depends on `--shard`. */
  | 'chunk'

export interface GroupShape {
  readonly shape: Shape
  readonly file: string
  readonly tests: number
  /** Group sizes with `fullyParallel: false` — the Playwright default. */
  readonly sequential: readonly number[]
  /** Group sizes with `fullyParallel: true`, under `--shard=k/3`. */
  readonly parallelAt3: readonly number[]
  /** The same file under `--shard=k/6`, which is where `chunk` gives itself away. */
  readonly parallelAt6: readonly number[]
  readonly sequentialUnit: Unit
  readonly parallelUnit: Unit
}

/**
 * Four shapes, eight cells, and one cell that is not a constant.
 *
 * Read the `hooked` row twice. Its groups are `[2, 2, 1]` at three shards and
 * `[1, 1, 1, 1, 1]` at six — the *grouping* is a function of the shard count,
 * not just the cut. One `test.beforeAll` is the whole difference between that
 * row and `plain` directly above it.
 */
export const GROUP_SHAPES: readonly GroupShape[] = [
  {
    shape: 'plain',
    file: 'plain.spec.ts',
    tests: 5,
    sequential: [5],
    parallelAt3: [1, 1, 1, 1, 1],
    parallelAt6: [1, 1, 1, 1, 1],
    sequentialUnit: 'file',
    parallelUnit: 'test',
  },
  {
    shape: 'hooked',
    file: 'hooked.spec.ts',
    tests: 5,
    sequential: [5],
    parallelAt3: [2, 2, 1],
    parallelAt6: [1, 1, 1, 1, 1],
    sequentialUnit: 'file',
    parallelUnit: 'chunk',
  },
  {
    shape: 'serial',
    file: 'serial.spec.ts',
    tests: 5,
    sequential: [5],
    parallelAt3: [5],
    parallelAt6: [5],
    sequentialUnit: 'file',
    parallelUnit: 'block',
  },
  {
    shape: 'parallel-block',
    file: 'parallel.spec.ts',
    tests: 4,
    sequential: [1, 1, 1, 1],
    parallelAt3: [1, 1, 1, 1],
    parallelAt6: [1, 1, 1, 1],
    sequentialUnit: 'test',
    parallelUnit: 'test',
  },
]

export interface Balance {
  readonly shards: number
  /** What `floor(total / n)` plus the remainder asks for: the even cut. */
  readonly nominal: readonly number[]
  /** What the groups allow, with `fullyParallel: false`. */
  readonly sequential: readonly number[]
  /** What the groups allow, with `fullyParallel: true`. */
  readonly parallel: readonly number[]
}

/**
 * The 23 tests of `fixture/specs/` (one project, no dependencies), cut n ways.
 *
 * The `nominal` column is what sharding advertises. The other two are what it
 * delivers. At four shards the default config produces `[8, 4, 10, 1]` against
 * a nominal `[6, 6, 6, 5]`: one machine does ten tests and another does one,
 * so four runners buy the wall clock of about two. At eight, `sequential` has
 * a shard with **no tests at all** — a runner booted, a repository cloned, a
 * browser downloaded, to run nothing.
 *
 * `fullyParallel: true` is the usual advice and it is not a fix. It makes the
 * groups finer, which moves every later group's starting index, which lands
 * `serial.spec.ts` — five tests that cannot be divided — somewhere else. Over
 * this fixture it improves the busiest shard at three (9 → 8), ties at two and
 * four, and makes it *worse* at six (5 → 6) and eight (5 → 7). Finer groups
 * are not more even groups.
 */
export const SHARD_BALANCE: readonly Balance[] = [
  { shards: 2, nominal: [12, 11], sequential: [12, 11], parallel: [12, 11] },
  { shards: 3, nominal: [8, 8, 7], sequential: [8, 9, 6], parallel: [8, 8, 7] },
  { shards: 4, nominal: [6, 6, 6, 5], sequential: [8, 4, 10, 1], parallel: [6, 6, 10, 1] },
  {
    shards: 6,
    nominal: [4, 4, 4, 4, 4, 3],
    sequential: [5, 3, 4, 5, 5, 1],
    parallel: [4, 4, 4, 4, 6, 1],
  },
  {
    shards: 8,
    nominal: [3, 3, 3, 3, 3, 3, 3, 2],
    sequential: [5, 3, 1, 3, 5, 5, 0, 1],
    parallel: [3, 3, 3, 3, 3, 7, 0, 1],
  },
]

/**
 * How many times the `setup` project runs, for the two-browser fixture shape.
 *
 * It is not a fraction of anything. Playwright detaches every project named in
 * another project's `dependencies`, shards what is left, and re-attaches the
 * dependency *in full* to every shard that kept a dependent test. So the
 * column below is the shard count, and a `setup` project that logs in against
 * a real identity provider is a cost you pay per machine — the one line of a
 * sharded config that gets more expensive the more you parallelise.
 */
export const SETUP_RUNS: readonly { readonly shards: number; readonly runs: number }[] = [
  { shards: 2, runs: 2 },
  { shards: 3, runs: 3 },
  { shards: 4, runs: 4 },
  { shards: 6, runs: 6 },
  { shards: 8, runs: 8 },
]

/** Total tests in the one-project fixture. */
export const FIXTURE_TEST_COUNT = FIXTURE_FILES.reduce((count, file) => count + file.titles.length, 0)

/**
 * The claims `README.md` makes, as predicates over the tables above.
 *
 * Each one is a function rather than a sentence so that changing a cell fails
 * a test before anybody reads the paragraph the cell contradicts.
 */
export const FINDINGS: Readonly<Record<string, () => boolean>> = {
  /** `fullyParallel` — a setting about workers — decides the shard unit. */
  'fully-parallel-decides-the-unit': () =>
    GROUP_SHAPES.some((row) => row.sequentialUnit === 'file' && row.parallelUnit !== 'file'),

  /** One `beforeAll` moves a file from per-test groups to shard-sized chunks. */
  'a-hook-changes-the-unit': () => {
    const plain = GROUP_SHAPES.find((row) => row.shape === 'plain')
    const hooked = GROUP_SHAPES.find((row) => row.shape === 'hooked')

    return (
      plain?.tests === hooked?.tests &&
      plain?.parallelUnit === 'test' &&
      hooked?.parallelUnit === 'chunk'
    )
  },

  /** And that chunk is sized by `--shard`, so the grouping is not fixed by the code. */
  'chunking-depends-on-the-shard-count': () => {
    const hooked = GROUP_SHAPES.find((row) => row.shape === 'hooked')

    return (
      hooked !== undefined &&
      JSON.stringify(hooked.parallelAt3) !== JSON.stringify(hooked.parallelAt6)
    )
  },

  /** A serial block is indivisible under every configuration measured. */
  'serial-never-splits': () =>
    GROUP_SHAPES.every(
      (row) =>
        row.shape !== 'serial' ||
        (row.sequential.length === 1 && row.parallelAt3.length === 1 && row.parallelAt6.length === 1),
    ),

  /** The default config misses the even cut it computed, at every shard count above two. */
  'the-default-config-misses-the-even-cut': () =>
    SHARD_BALANCE.filter(
      (row) => JSON.stringify(row.sequential) !== JSON.stringify(row.nominal),
    ).length ===
    SHARD_BALANCE.filter((row) => row.shards > 2).length,

  /**
   * And `fullyParallel: true` does not simply fix it. Finer groups change
   * where *every later group starts*, so an indivisible block lands somewhere
   * else — better at three shards, worse at six and eight. Balance is not
   * monotone in group granularity, which is the opposite of the folklore.
   */
  'fully-parallel-is-not-monotone': () =>
    SHARD_BALANCE.some((row) => Math.max(...row.parallel) < Math.max(...row.sequential)) &&
    SHARD_BALANCE.some((row) => Math.max(...row.parallel) > Math.max(...row.sequential)),

  /** Neither config reaches the even cut once the shard count passes three. */
  'neither-config-reaches-the-even-cut': () =>
    SHARD_BALANCE.filter((row) => row.shards > 3).every(
      (row) =>
        Math.max(...row.sequential) > Math.max(...row.nominal) &&
        Math.max(...row.parallel) > Math.max(...row.nominal),
    ),

  /** Past a point, a shard is a machine that runs nothing. */
  'over-sharding-produces-empty-shards': () =>
    SHARD_BALANCE.some((row) => row.sequential.includes(0) || row.parallel.includes(0)),

  /** The critical path is bounded below by the largest group, not by `total / n`. */
  'the-largest-group-is-the-floor': () => {
    const largest = Math.max(
      ...GROUP_SHAPES.map((row) => Math.max(...row.parallelAt6)),
    )

    return SHARD_BALANCE.every(
      (row) => row.shards < 4 || Math.max(...row.parallel) >= largest,
    )
  },

  /** A dependency project is multiplied by the shard count, not divided by it. */
  'dependencies-run-once-per-shard': () => SETUP_RUNS.every((row) => row.runs === row.shards),
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function row(cells: readonly string[]): string {
  return `| ${cells.join(' | ')} |`
}

const sizes = (group: readonly number[]): string => `\`[${group.join(', ')}]\``

/**
 * The grouping table as README markdown.
 *
 * Rendered rather than transcribed, on the same argument
 * `intercept/matrix.ts` makes: `readme.test.ts` compares the string, so a
 * published table cannot disagree with the measurement it claims to be.
 */
export function renderShapesTable(): string {
  return [
    row(['file', 'tests', '`fullyParallel: false`', '`fullyParallel: true`, 3 shards', 'at 6 shards', 'unit']),
    row(['---', '---', '---', '---', '---', '---']),
    ...GROUP_SHAPES.map((shape) =>
      row([
        `\`${shape.file}\``,
        String(shape.tests),
        sizes(shape.sequential),
        sizes(shape.parallelAt3),
        sizes(shape.parallelAt6),
        `\`${shape.sequentialUnit}\` → \`${shape.parallelUnit}\``,
      ]),
    ),
  ].join('\n')
}

/** The balance table as README markdown. */
export function renderBalanceTable(): string {
  return [
    row(['shards', 'even cut', '`fullyParallel: false`', '`fullyParallel: true`', 'setup runs']),
    row(['---', '---', '---', '---', '---']),
    ...SHARD_BALANCE.map((balance) =>
      row([
        String(balance.shards),
        sizes(balance.nominal),
        sizes(balance.sequential),
        sizes(balance.parallel),
        String(SETUP_RUNS.find((entry) => entry.shards === balance.shards)?.runs ?? 0),
      ]),
    ),
  ].join('\n')
}
